<!DOCTYPE html>
<html lang="pt_br">
<head>
    <meta http-equiv="contet type" content="text/html;charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit-no">

    <link rel="stylesheet" href="public/css/bootstraop.min.css">

    <title><?php echo $noticia["titulo"] ?></title>
</head>
<body>
    <div class="container">
        
        <h1><?php echo $noticia["titulo"] ?></h1>
        <p><?php echo $noticia["conteudo"] ?></p>
    </div>
</body>
</html>